# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
version: "3.3"

# Servidor nginx
services:
  web:
    image: nginx:latest
    # Puerto 8080 
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: cursophp
        MYSQL_DATABASE: cursophp
        MYSQL_USER: cursophp
        MYSQL_PASSWORD: cursophp
    ports:
        - "3306:3306"
  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html
